Bug Fixes. Added colors to output. Added features

diff --git a/src/checkers/compile_student b/src/checkers/compile_student
--- a/src/checkers/compile_student
+++ b/src/checkers/compile_student
@@ -20,10 +20,10 @@ function warnEdits() {
 
 function warnTests() {
         if grep -q "warning:" "$OUTFILE"; then
-                echo "Submission produced a warning. Good!"
+                echo -e "${GRN}Submission produced a warning. Good!${NC}"
                 exit 0
         else
-                echo "Submission did not produce a warning. Bad!"
+                echo -e "${RED}Submission did not produce a warning. Bad!${NC}"
                 exit 1
         fi
 }
@@ -38,10 +38,10 @@ function errorEdits() {
 
 function errorTests() {
         if grep -q 'No errors, Good Job!' "$OUTFILE"; then
-                echo "Submission did not produce an error. Bad!"
+                echo -e "${RED}Submission did not produce an error. Bad!${NC}"
                 exit 1
         else
-                echo "Submission produced an error. Good!"
+                echo -e "${GRN}Submission produced an error. Good!${NC}"
                 exit 0
         fi
 }
@@ -58,10 +58,10 @@ function stopEdits() {
 
 function stopTests() {
         if egrep -q -i "(stop|stop.)" "$OUTFILE"; then
-                echo "Submission produced a stopping condition. Good!"
+                echo -e "${GRN}Submission produced a stopping condition. Good!${NC}"
                 exit 0
         else
-                echo "Submission did not produce a stopping condition. Bad!"
+                echo -e "${RED}Submission did not produce a stopping condition. Bad!${NC}"
                 exit 1
         fi
 }
@@ -70,15 +70,31 @@ function badEdits() {
         # TODO This doesn't work if there's no makefile
         #      Not sure how to fix
         sed -i -e "s/$EXECUTABLE/bad_exec/" Makefile
+
+        # Maybe something like:
+        # if [[ ${COMPILE_CMND[0]} != "make" ]]; then
+        #         len="${#COMPILE_CMND[@]}"
+        #         for (( i=0; i<len; i++ )) do
+        #                 if [[ "${COMPILE_CMND[i]}" == "-o" ]]; then
+        #                         COMPILE_CMND[i+1]="bad_exec"
+        #                         break
+        #                 fi
+        #         done
+        # else
+        #         sed -i -e "s/$EXECUTABLE/bad_exec/" Makefile
+        # fi
+        # 
+        # But I don't think we need this since we can't assert an exec with
+        # anything but a Makefile
 }
 
 function badTests() {
         IMPROPERLY_NAMED="Your program built but was improperly named"
         if grep -q "$IMPROPERLY_NAMED" "$OUTFILE"; then
-                echo "Submission produced a bad executable name. Good!"
+                echo -e "${GRN}Submission produced a bad executable name. Good!${NC}"
                 exit 0
         else
-                echo "Submission did not produce a bad executable name. Bad!"
+                echo -e "${RED}Submission did not produce a bad executable name. Bad!${NC}"
                 exit 1
         fi
 }
@@ -91,7 +107,15 @@ function performEdits() {
 
         # Bad executable test only applies if we assert an executable name
         # https://stackoverflow.com/questions/3601515/13864829#13864829
-        [[ -z ${EXECUTABLE+x} ]] && toRun+=("bad")
+
+        # TODO: This wasn't working, though it is much more elegant than the
+        #       working code below
+        # [[ -z ${EXECUTABLE+x} ]] && toRun+=("bad")
+
+        if [[ "$EXECUTABLE" != "" ]]; then
+                toRun+=("bad")
+        fi
+                
 
         for test in "${toRun[@]}"; do
                 mkdir "$test"
@@ -103,10 +127,11 @@ function performEdits() {
 }
 
 function performTests() {
-        echo "~~~~~~~~ Compile Student Test ~~~~~~~~~~~~"
-
+        echo -e "~~~~~~~~~~ ${LB}Compile Student Test${NC} ~~~~~~~~~~~~"
         for directory in */; do
                 (cd "$directory" && "$(basename "$directory")"Tests)
+                assert_test "$?" "${directory%/*}" "${directory%/*}" 4
+                # [[ "$?" == 1 ]] && exit 1
         done
 }
 
