bug fixes and better error messaging

diff --git a/src/checkers/compile_student b/src/checkers/compile_student
--- a/src/checkers/compile_student
+++ b/src/checkers/compile_student
@@ -8,6 +8,8 @@ fi
 COMPILE_CMND=("${@:1}")
 OUTFILE=provide_output.txt
 
+
+
 function warnEdits() {
 
         WARN_CONDITION="static bool wrn5611d9f99bc990c23027ca70b7aba2(int wrne9cc6) {}"
@@ -57,6 +59,8 @@ function stopEdits() {
 }
 
 function stopTests() {
+        
+        
         if egrep -q -i "(stop|stop.)" "$OUTFILE"; then
                 echo -e "${GRN}Submission produced a stopping condition. Good!${NC}"
                 exit 0
@@ -64,32 +68,16 @@ function stopTests() {
                 echo -e "${RED}Submission did not produce a stopping condition. Bad!${NC}"
                 exit 1
         fi
+        
 }
 
 function badEdits() {
-        # TODO This doesn't work if there's no makefile
-        #      Not sure how to fix
         sed -i -e "s/$EXECUTABLE/bad_exec/" Makefile
-
-        # Maybe something like:
-        # if [[ ${COMPILE_CMND[0]} != "make" ]]; then
-        #         len="${#COMPILE_CMND[@]}"
-        #         for (( i=0; i<len; i++ )) do
-        #                 if [[ "${COMPILE_CMND[i]}" == "-o" ]]; then
-        #                         COMPILE_CMND[i+1]="bad_exec"
-        #                         break
-        #                 fi
-        #         done
-        # else
-        #         sed -i -e "s/$EXECUTABLE/bad_exec/" Makefile
-        # fi
-        # 
-        # But I don't think we need this since we can't assert an exec with
-        # anything but a Makefile
 }
 
 function badTests() {
         IMPROPERLY_NAMED="Your program built but was improperly named"
+
         if grep -q "$IMPROPERLY_NAMED" "$OUTFILE"; then
                 echo -e "${GRN}Submission produced a bad executable name. Good!${NC}"
                 exit 0
@@ -97,26 +85,29 @@ function badTests() {
                 echo -e "${RED}Submission did not produce a bad executable name. Bad!${NC}"
                 exit 1
         fi
+
 }
 
 function performEdits() {
         toRun=("warn" "error")
 
-        # Stop condition test only applies if we have a makefile
-        [[ "${COMPILE_CMND[0]}" == "make" ]] && toRun+=("stop")
-
-        # Bad executable test only applies if we assert an executable name
-        # https://stackoverflow.com/questions/3601515/13864829#13864829
-
-        # TODO: This wasn't working, though it is much more elegant than the
-        #       working code below
-        # [[ -z ${EXECUTABLE+x} ]] && toRun+=("bad")
-
-        if [[ "$EXECUTABLE" != "" ]]; then
-                toRun+=("bad")
+        # Stop condition only applies if we have a makefile
+        # Bad executable only applies if compilation command is exactly "make"
+        # with no target specified
+        if [[ "${COMPILE_CMND[0]}" == "make" ]]; then
+                toRun+=("stop") 
+                if [[ "${#COMPILE_CMND[@]}" -lt 2 ]]; then
+                        toRun+=("bad")
+                else 
+                        echo -e "${YLW}A make target was specified, "
+                        echo -e "or a custom compilation command was used."
+                        echo -e "Unable to perform 'bad' test.${NC}"
+                        echo ""
+                fi
         fi
-                
-
+        
+        
+           
         for test in "${toRun[@]}"; do
                 mkdir "$test"
                 # idk why I can't use "-exec ... +" here
@@ -130,8 +121,7 @@ function performTests() {
         echo -e "~~~~~~~~~~ ${LB}Compile Student Test${NC} ~~~~~~~~~~~~"
         for directory in */; do
                 (cd "$directory" && "$(basename "$directory")"Tests)
-                assert_test "$?" "${directory%/*}" "${directory%/*}" 4
-                # [[ "$?" == 1 ]] && exit 1
+                assert_test "$?" "${directory%/*}" "${directory%/*}"
         done
 }
 
